#dockerfile backend

#base image
FROM node:lts-slim

#commands execute in this directory
WORKDIR /app

#copy dependencies into image
COPY ./package.json ./

#install dependencies
RUN npm install react-scripts@latest

#copy project files
COPY . .

#default argument
CMD [ "node", "server.js" ]