apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGODB_URL: "mongodb+srv://amazona:LErZYInFpNRkmwq3@sridavid.jl1nmyf.mongodb.net/?appName=sridavid"
  JWT_SECRET: "amazona-jwt-secret-2024-rayudu"
  PAYPAL_CLIENT_ID: "optional"
