FROM node:16-alpine

WORKDIR /app

# Copy package files from root
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy backend folder
COPY backend ./backend

# Set working directory to backend
WORKDIR /app/backend

# Expose port
EXPOSE 5000

# Start server
CMD ["node", "server.js"]
