name: frontend and backend

on:
    push:
        branches:
            feature

jobs:
    job1:
        runs-on: ubuntu-24.04-arm
        
        steps:
            - name: copy latest code to pipeline
              uses: actions/checkout@v4

            - name: setup backend
              uses: actions/setup-node@v6
              with: 
                node-version: "24"
            
            - name: install dependencies
              run:  npm install
             
            - name: change directory
              run: cd backend 

            - name: build files
              run: npm  build

            
            
