name: frontend and backend

on:
    push:
        branches:
            feature

jobs:
    job1:
        runs-on: ubuntu-24.04-arm
        
        steps:
            - name: copy latest code to pipeline
              uses: actions/checkout@v4

            - name: setup backend
              uses: cybergavin/setup-nodejs-project@v1
              with: 
                lock-file: ./package.json
                working-directory: backend
            
            
